# Packages de données spatiales

De nombreux packages de mise à disposition de données géographiques (géométries et/ou attributs) ont été développés. Il s'agit le plus souvent de packages interfaçant des API qui permettent d'interroger des données mises à disposition sur le Web, directement avec R.

**Ce chapitre en présente une liste non exhaustive.**

## À l'échelle mondiale

- {{< fa globe >}} `rnaturalearth` [@R-rnaturalearth] : permet de récupérer les données cartographiques [Natural Earth](https://www.naturalearthdata.com/).   
- {{< fa globe >}} `cshapes` [@R-cshapes] : met à disposition les frontières nationales, de 1886 à aujourd'hui.  
- {{< fa globe >}} `osmextract` [@R-osmextract] : permet d'importer des données [OpenStreetMap](https://www.openstreetmap.org/).   
- {{< fa globe >}} `osmdata` [@R-osmdata] : pour télécharger et utiliser les données d'OpenStreetMap.
- {{< fa globe >}} `maptiles` [@R-maptiles] : Ce package télécharge, compose et affiche des tuiles à partir d'un grand nombre de fournisseurs (*OpenStreetMap*, *Stadia*, *Esri*, *CARTO* ou *Thunderforest*...).   
- {{< fa table >}} `geonames` [@R-geonames] : permet d'interroger la BD [geonames](http://www.geonames.org/), qui fournit notamment des localisations.
- {{< fa table >}} `wbstats` [@R-wbstats] et `WDI` [@R-WDI] : donnent accès aux données et statistiques de la Banque mondiale.   
- {{< fa globe >}} `sen2r` [@R-sen2r] : permet de télécharger et prétraiter automatiquement les données du satellite Sentinel-2.   
- {{< fa globe >}} `MODIStsp` [@R-MODIStsp] : permet de trouver, télécharger et traiter des images *MODIS*.
- {{< fa globe >}} `geodata` [@R-geodata] : founit un accès à des [données](https://github.com/rspatial/geodata) sur le climat, l'altitude, le sol, la présence d'espèces et les limites administratives. 
- {{< fa globe >}} `elevatr` [@R-elevatr] : donne accès à des données d'élévation mises à disposition par [*Amazon Web Services Terrain Tiles*](https://registry.opendata.aws/terrain-tiles/), l'[*Open Topography Global Datasets API*](https://opentopography.org/developers/) et l'[*USGS Elevation Point Query Service*](https://nationalmap.gov/epqs/).
- {{< fa globe >}} `rgee` [@R-rgee] : permet d'utiliser l'API de [Google Earth Engine](https://www.google.com/intl/fr_in/earth/education/tools/google-earth-engine/), catalogue de données publiques et infrastructure de calcul pour les images satellites.   
- {{< fa globe >}} `nasapower` [@R-nasapower] : API client *NASA* (prévision des ressources énergétiques mondiales, météorologie, énergie solaire de surface et climatologie). 
- {{< fa globe >}} `geoknife` [@R-geoknife] : permet de traiter (en ligne) des données matricielles volumineuses issues du *Geo Data Portal* de l'*U.S. Geological Survey*.
- {{< fa globe >}} {{< fa table >}} `rdhs` [@R-rdhs] : API client et gestions de données de l'[enquête démographique et de santé (DHS)](https://dhsprogram.com/).




## À l'échelle européenne

- {{< fa globe >}} `giscoR` [@R-giscoR] : permet de télécharger des données cartographiques mondiales et européennes de la BD [GISCO](https://ec.europa.eu/eurostat/web/gisco) d'Eurostat (système d'information géographique de la Commission). 
- {{< fa table >}} `eurostat` [@R-eurostat] : permet de télécharger des données de la BD [Eurostat](https://ec.europa.eu/eurostat).    
  


## À l'échelle nationale



- **Brésil**
  - {{< fa globe >}} `geobr` [@R-geobr] : fournit un accès facile aux séries de données spatiales officielles du Brésil pour différentes années et découpages administratifs. 
- **Chili**
  - {{< fa globe >}} `chilemapas` [@R-chilemapas] : donne accès aux  divisions politiques et administratives du Chili. 
- **Espagne** 
  - {{< fa globe >}} `mapSpain` [@R-mapSpain] : propose les limites administratives de l'Espagne à plusieurs niveaux (Communautés autonomes, Provinces, Municipalités), ainsi que des tuiles.
- **États-Unis**
  - {{< fa globe >}} {{< fa table >}} `tidycensus` [@R-tidycensus] : permet de charger des données et géométries du recensement américain en format `sf` et `tidyverse`
  - {{< fa globe >}} `tigris` [@R-tigris] : donne accès aux éléments cartographiques fournis par le US Census Bureau TIGER, y compris les limites cartographiques, les routes et l'eau.
  - {{< fa globe >}} {{< fa table >}} `FedData` [@R-FedData] : automatise le téléchargement de données géospatiales disponibles à partir de plusieurs sources de données fédérées.
  - {{< fa table >}} `acs` [@R-acs] : permet de télécharger et manipuler les données de l'*American Community Survey* et les données décennales du recensement des États-Unis.
  - {{< fa table >}} `censusapi` [@R-censusapi] : wrapper pour les API du *Census Bureau* des États-Unis.
  - {{< fa table >}} `idbr` [@R-idbr] : interface avec l'API de la base de données internationale du US Census Bureau.  
  - {{< fa table >}} `ipumsr` [@R-ipumsr] : Permet d'importer des données de recensement, d'enquête et géographiques fournies par l'[IPUMS](https://www.ipums.org/).
  - {{< fa table >}} `totalcensus` [@R-totalcensus] : permet d'extraire les données du recensement décennal et de l'*American Community Survey* au niveaux des *block*, *block group* et *tract*.
- **Finland**
  - {{< fa globe >}} `mapsFinland` [@R-mapsFinland] : donne un accès à des cartes et données concernant la Finlande.
- **France**
  - {{< fa globe >}} `happign` [@R-happign] : accès à certaines données de l'IGN.
  - {{< fa globe >}} `insee` [@R-insee] : pour télécharger facilement les données de la base BDM ([Banque de Données Macroéconomiques](https://www.data.gouv.fr/fr/reuses/insee-package-r/)) de l'INSEE.
- **Pologne**
  - {{< fa globe >}} `rgugik` [@R-rgugik] : permet l'acquisition automatique de données ouvertes à partir des ressources du Bureau central polonais de la géodésie et de la cartographie ([Główny Urząd Geodezji i Kartografii](https://www.gov.pl/web/gugik) ).  
- **Uruguay**
  - {{< fa globe >}} `geouy` [@R-geouy] : permet le chargement d'informations géographiques sur l'Uruguay.
- ...





