# *Préambule* {.unnumbered}

Ce manuel est destiné tant aux utilisateurs de R souhaitant mettre en place des traitements de données spatiales qu'aux utilisateurs souhaitant utiliser R pour réaliser les taches qu'ils réalisent habituellement avec un SIG.   
Les principales étapes du traitement de l'information géographiques y sont abordées. 
L'accent est porté sur le traitement des données vectorielles mais une partie est tout de même dédiée aux données raster. 

**Comment utiliser le manuel**  
Les données utilisées dans ce document sont stockées dans un projet RStudio. 
Vous devez le télécharger puis le décompresser sur votre machine. Il vous sera ensuite possible de tester l'ensemble des manipulations proposées dans ce document au sein du projet **geodata**.  
[Télécharger le projet](geodata.zip){.btn .btn-primary .btn-sm role="button"}  


**Contribution et feedback**  
Vous pouvez nous envoyer vos remarques et suggestions en [postant une *issue*](https://github.com/rCarto/geomatique_avec_r/issues) sur le [dépôt GitHub](https://github.com/rCarto/geomatique_avec_r) de ce document. 

**Contexte**  
Ce manuel a été initialement conçu pour accompagner le cours "Cartographie avec R" 
du Master 2 Géomatique, géodécisionnel, géomarketing et multimédia (G2M) de 
l'Université Paris 8 Vincennes - Saint-Denis. 
Un deuxième manuel centré sur la cartographie est disponible ici :
[Cartographie avec R](https://rcarto.github.io/cartographie_avec_r/).

--------
<small>
**Pour citer le document :**  

Giraud, T. et Pecout, H. (2023). Géomatique avec R. https://doi.org/10.5281/zenodo.5906212

```
@misc{
  author = {Giraud, Timothée and Pecout, Hugues},
  doi = {10.5281/zenodo.5906212},
  title = {{Géomatique avec R}},
  url = {https://rcarto.github.io/geomatique_avec_r/},
  year = {2023}
}
```
</small>
